# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ress.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QAction, QMainWindow
from push import Ui_WindowPush, get_result


class Ui_MainResults(QMainWindow):

    def open_sec_window(self):
        print(1)
        self.sec_window = QMainWindow()
        self.sec_ui = Ui_WindowPush()
        self.sec_ui.setupUi(self.sec_window)
        self.sec_window.show()

    def lab(self):
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 71, 21))
        fontt = QtGui.QFont()
        fontt.setFamily("Arial Black")
        fontt.setPointSize(12)
        fontt.setBold(True)
        fontt.setWeight(75)
        self.label.setFont(fontt)
        self.label.setObjectName("label")
        # _translate = QtCore.QCoreApplication.translate
        self.label.setText('OKEE')

    def setupUi(self, MainResults):
        MainResults.setObjectName("MainResults")
        MainResults.resize(340, 320)
        self.centralwidget = QtWidgets.QWidget(MainResults)
        self.centralwidget.setObjectName("centralwidget")
        self.afternoon = QtWidgets.QLabel(self.centralwidget)
        self.afternoon.setGeometry(QtCore.QRect(120, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.afternoon.setFont(font)
        self.afternoon.setObjectName("afternoon")
        self.evening = QtWidgets.QLabel(self.centralwidget)
        self.evening.setGeometry(QtCore.QRect(230, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.evening.setFont(font)
        self.evening.setObjectName("evening")
        self.morning = QtWidgets.QLabel(self.centralwidget)
        self.morning.setGeometry(QtCore.QRect(20, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.morning.setFont(font)
        self.morning.setObjectName("morning")
        self.scroll = QtWidgets.QScrollBar(self.centralwidget)
        self.scroll.setGeometry(QtCore.QRect(320, 0, 16, 320))
        self.scroll.setOrientation(QtCore.Qt.Vertical)
        self.scroll.setObjectName("scroll")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(100, 0, 16, 320))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(210, 0, 16, 320))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainResults.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainResults)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 340, 21))
        self.menubar.setObjectName("menubar")
        # self.menuImport = QtWidgets.QMenu(self.menubar)
        self.imp = self.menubar.addMenu('Import')
        self.actImp = QAction('Import', self)
        self.imp.addAction(self.actImp)
        # self.menuImport.setObjectName("menuImport")
        self.menuDelete = QtWidgets.QMenu(self.menubar)
        self.menuDelete.setObjectName("menuDelete")
        MainResults.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainResults)
        self.statusbar.setObjectName("statusbar")
        MainResults.setStatusBar(self.statusbar)
        # self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuDelete.menuAction())

        self.retranslateUi(MainResults)
        QtCore.QMetaObject.connectSlotsByName(MainResults)

        self.actImp.triggered.connect(lambda: self.open_sec_window())

    def retranslateUi(self, MainResults):
        _translate = QtCore.QCoreApplication.translate
        MainResults.setWindowTitle(_translate("MainResults", "MainWindow"))
        self.afternoon.setText(_translate("MainResults", "Afternoon"))
        self.evening.setText(_translate("MainResults", "Evening"))
        self.morning.setText(_translate("MainResults", "Morning"))
        # self.menuImport.setTitle(_translate("MainResults", "Import"))
        self.menuDelete.setTitle(_translate("MainResults", "Delete"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainResults = QtWidgets.QMainWindow()
    ui = Ui_MainResults()
    ui.setupUi(MainResults)
    MainResults.show()
    sys.exit(app.exec_())
