# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ressEdited.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QAction, QMainWindow
from push import Ui_WindowPush
from data import get_part_of_day


class Ui_MainResults(QMainWindow):

    def open_sec_window(self):
        print(1)
        self.sec_window = QMainWindow()
        self.sec_ui = Ui_WindowPush()
        self.sec_ui.setupUi(self.sec_window)
        self.sec_window.show()
        self.adder(self.sec_ui)
        # print(self.sec_ui.res)

    def delete_result(self):

        try:
            if len(self.listWidget_af.selectedItems()) == 0 and len(self.listWidget_ev.selectedItems()) == 0:
                self.listWidget_mr.takeItem(self.listWidget_mr.row(self.listWidget_mr.selectedItems()[0]))
            elif len(self.listWidget_mr.selectedItems()) == 0 and len(self.listWidget_ev.selectedItems()) == 0:
                self.listWidget_af.takeItem(self.listWidget_af.row(self.listWidget_af.selectedItems()[0]))
            elif len(self.listWidget_mr.selectedItems()) == 0 and len(self.listWidget_af.selectedItems()) == 0:
                self.listWidget_ev.takeItem(self.listWidget_ev.row(self.listWidget_ev.selectedItems()[0]))
        except IndexError:
            pass

    def setupUi(self, MainResults):
        MainResults.setObjectName("MainResults")
        MainResults.resize(347, 320)
        self.centralwidget = QtWidgets.QWidget(MainResults)
        self.centralwidget.setObjectName("centralwidget")
        self.afternoon = QtWidgets.QLabel(self.centralwidget)
        self.afternoon.setGeometry(QtCore.QRect(120, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.afternoon.setFont(font)
        self.afternoon.setObjectName("afternoon")
        self.evening = QtWidgets.QLabel(self.centralwidget)
        self.evening.setGeometry(QtCore.QRect(240, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.evening.setFont(font)
        self.evening.setObjectName("evening")
        self.morning = QtWidgets.QLabel(self.centralwidget)
        self.morning.setGeometry(QtCore.QRect(20, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.morning.setFont(font)
        self.morning.setObjectName("morning")
        self.scroll = QtWidgets.QScrollBar(self.centralwidget)
        self.scroll.setGeometry(QtCore.QRect(330, 0, 16, 320))
        self.scroll.setOrientation(QtCore.Qt.Vertical)
        self.scroll.setObjectName("scroll")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(100, 0, 16, 320))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(210, 0, 16, 320))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 39, 91, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_mr = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget_mr.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget_mr)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(230, 40, 91, 241))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget_ev = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.listWidget_ev.setObjectName("listWidget_3")
        self.verticalLayout_2.addWidget(self.listWidget_ev)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(120, 40, 91, 241))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget_af = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        self.listWidget_af.setObjectName("listWidget_2")
        self.verticalLayout_3.addWidget(self.listWidget_af)
        MainResults.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainResults)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 347, 21))
        self.menubar.setObjectName("menubar")

        self.imp = self.menubar.addMenu('Actions')
        self.actImp = QAction('Import', self)
        self.imp.addAction(self.actImp)

        self.deleteImp = QAction('Delete', self)
        self.imp.addAction(self.deleteImp)

        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menuDelete = QtWidgets.QMenu(self.menubar)
        self.menuDelete.setObjectName("menuDelete")
        MainResults.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainResults)
        self.statusbar.setObjectName("statusbar")
        MainResults.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuDelete.menuAction())

        self.retranslateUi(MainResults)
        QtCore.QMetaObject.connectSlotsByName(MainResults)

        self.actImp.triggered.connect(lambda: self.open_sec_window())
        self.deleteImp.triggered.connect(lambda: self.delete_result())

    def retranslateUi(self, MainResults):
        _translate = QtCore.QCoreApplication.translate
        MainResults.setWindowTitle(_translate("MainResults", "MainWindow"))
        self.afternoon.setText(_translate("MainResults", "Afternoon"))
        self.evening.setText(_translate("MainResults", "Evening"))
        self.morning.setText(_translate("MainResults", "Morning"))
        # self.menuImport.setTitle(_translate("MainResults", "Import"))
        # self.menuDelete.setTitle(_translate("MainResults", "Delete"))

    def adder(self, WindowPush):
        self.sec_ui.pushButton.clicked.connect(lambda: self.push(WindowPush))

    def push(self, window):
        self.res = self.sec_ui.lineEdit.text()

        res = QtWidgets.QListWidgetItem(self.res)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        res.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
        res.setFont(font)

        if get_part_of_day() == 'morning':
            self.listWidget_mr.addItem(res)
        elif get_part_of_day() == 'afternoon':
            self.listWidget_af.addItem(res)
        elif get_part_of_day() == 'evening':
            self.listWidget_ev.addItem(res)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainResults = QtWidgets.QMainWindow()
    ui = Ui_MainResults()
    ui.setupUi(MainResults)
    MainResults.show()
    sys.exit(app.exec_())
